-- =============================================================================
-- Serving-layer warehouse for the real-time fraud pipeline (PostgreSQL 15+)
--
--   dw       star schema: conformed dimensions + transaction/alert/chargeback facts
--   staging  unlogged landing tables used by bulk loads (SCD2 merge input)
--   ops      pipeline observability: micro-batch metrics, reconciliation audit
--
-- The lakehouse (Delta Lake) is the system of record; this database is a
-- serving copy that the streaming job keeps current with idempotent upserts and
-- that the nightly reconciliation job can backfill at any time.
-- =============================================================================

DO $$ BEGIN
    EXECUTE format('ALTER DATABASE %I SET timezone TO %L', current_database(), 'UTC');
END $$;
SET timezone TO 'UTC';

CREATE SCHEMA IF NOT EXISTS dw;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS ops;

-- -----------------------------------------------------------------------------
-- Helper functions
-- -----------------------------------------------------------------------------

-- Great-circle distance in km (matches common/geo.py).
CREATE OR REPLACE FUNCTION dw.haversine_km(
    lat1 double precision, lon1 double precision,
    lat2 double precision, lon2 double precision
) RETURNS double precision
LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT AS $$
    SELECT 2 * 6371.0088 * asin(least(1.0, sqrt(
        power(sin(radians(lat2 - lat1) / 2), 2)
        + cos(radians(lat1)) * cos(radians(lat2)) * power(sin(radians(lon2 - lon1) / 2), 2)
    )))
$$;

CREATE OR REPLACE FUNCTION dw.to_date_key(ts timestamptz)
RETURNS integer LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT AS $$
    SELECT (to_char(ts AT TIME ZONE 'UTC', 'YYYYMMDD'))::integer
$$;

-- -----------------------------------------------------------------------------
-- Dimensions
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS dw.dim_date (
    date_key      integer     PRIMARY KEY,           -- YYYYMMDD smart key
    full_date     date        NOT NULL UNIQUE,
    day_of_week   smallint    NOT NULL,              -- ISO: 1 = Monday
    day_name      text        NOT NULL,
    day_of_month  smallint    NOT NULL,
    day_of_year   smallint    NOT NULL,
    iso_week      smallint    NOT NULL,
    month_num     smallint    NOT NULL,
    month_name    text        NOT NULL,
    quarter_num   smallint    NOT NULL,
    year_num      smallint    NOT NULL,
    is_weekend    boolean     NOT NULL
);

INSERT INTO dw.dim_date
SELECT to_char(d, 'YYYYMMDD')::integer,
       d::date,
       extract(isodow FROM d)::smallint,
       trim(to_char(d, 'Day')),
       extract(day FROM d)::smallint,
       extract(doy FROM d)::smallint,
       extract(week FROM d)::smallint,
       extract(month FROM d)::smallint,
       trim(to_char(d, 'Month')),
       extract(quarter FROM d)::smallint,
       extract(year FROM d)::smallint,
       extract(isodow FROM d) IN (6, 7)
FROM generate_series(date '2020-01-01', date '2035-12-31', interval '1 day') AS g(d)
ON CONFLICT (date_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS dw.dim_location (
    location_key   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city           text             NOT NULL,
    country_code   char(2)          NOT NULL,
    latitude       double precision NOT NULL,
    longitude      double precision NOT NULL,
    currency_code  char(3)          NOT NULL,
    UNIQUE (city, country_code)
);

CREATE TABLE IF NOT EXISTS dw.dim_merchant_category (
    mcc            char(4) PRIMARY KEY,               -- ISO 18245 merchant category code
    category_name  text    NOT NULL,
    risk_tier      text    NOT NULL CHECK (risk_tier IN ('LOW', 'MEDIUM', 'HIGH', 'UNKNOWN'))
);

CREATE TABLE IF NOT EXISTS dw.dim_currency (
    currency_code  char(3)        PRIMARY KEY,
    usd_per_unit   numeric(18, 8) NOT NULL CHECK (usd_per_unit > 0),
    minor_units    smallint       NOT NULL
);

CREATE TABLE IF NOT EXISTS dw.dim_dispute_reason (
    reason_code    text    PRIMARY KEY,
    description    text    NOT NULL,
    is_fraud       boolean NOT NULL
);

-- Cardholders: SCD Type 2 so facts keep the attributes that were true at swipe time.
CREATE TABLE IF NOT EXISTS dw.dim_users (
    user_key            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             text             NOT NULL,
    card_id             text             NOT NULL,
    home_location_key   integer          NOT NULL,
    home_city           text             NOT NULL,
    home_country_code   char(2)          NOT NULL,
    home_lat            double precision NOT NULL,
    home_lon            double precision NOT NULL,
    card_network        text             NOT NULL,
    card_tier           text             NOT NULL,
    segment             text             NOT NULL,
    account_open_date   date             NOT NULL,
    credit_limit_usd    numeric(12, 2)   NOT NULL,
    has_chip_card       boolean          NOT NULL,
    row_hash            text             NOT NULL,     -- md5 of tracked attributes
    valid_from          timestamptz      NOT NULL DEFAULT now(),
    valid_to            timestamptz      NOT NULL DEFAULT 'infinity',
    is_current          boolean          NOT NULL DEFAULT true
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_users_current ON dw.dim_users (user_id) WHERE is_current;
CREATE INDEX IF NOT EXISTS ix_dim_users_segment ON dw.dim_users (segment) WHERE is_current;

-- Merchants: SCD Type 1 (overwrite) - history is not analytically relevant.
CREATE TABLE IF NOT EXISTS dw.dim_merchants (
    merchant_key    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id     text             NOT NULL UNIQUE,
    merchant_name   text             NOT NULL,
    mcc             char(4)          NOT NULL REFERENCES dw.dim_merchant_category (mcc),
    location_key    integer,
    city            text,
    country_code    char(2),
    latitude        double precision,
    longitude       double precision,
    is_online       boolean          NOT NULL,
    updated_at      timestamptz      NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_dim_merchants_mcc ON dw.dim_merchants (mcc);

-- Kimball "unknown member" rows so late-arriving dimensions never drop facts.
INSERT INTO dw.dim_location (location_key, city, country_code, latitude, longitude, currency_code)
VALUES (-1, 'Unknown', '??', 0, 0, 'USD') ON CONFLICT DO NOTHING;
INSERT INTO dw.dim_merchant_category VALUES ('0000', 'Unknown', 'UNKNOWN') ON CONFLICT DO NOTHING;
INSERT INTO dw.dim_users (user_key, user_id, card_id, home_location_key, home_city, home_country_code,
                          home_lat, home_lon, card_network, card_tier, segment, account_open_date,
                          credit_limit_usd, has_chip_card, row_hash, valid_from)
VALUES (-1, 'UNKNOWN', 'UNKNOWN', -1, 'Unknown', '??', 0, 0, 'UNKNOWN', 'UNKNOWN', 'UNKNOWN',
        date '1970-01-01', 0, true, 'unknown', '-infinity')
ON CONFLICT DO NOTHING;
INSERT INTO dw.dim_merchants (merchant_key, merchant_id, merchant_name, mcc, location_key, is_online)
VALUES (-1, 'UNKNOWN', 'Unknown', '0000', -1, false) ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- Staging + SCD2 merge
-- -----------------------------------------------------------------------------

CREATE UNLOGGED TABLE IF NOT EXISTS staging.users (
    user_id            text PRIMARY KEY,
    card_id            text,
    home_city          text,
    home_country_code  char(2),
    card_network       text,
    card_tier          text,
    segment            text,
    account_open_date  date,
    credit_limit_usd   numeric(12, 2),
    has_chip_card      boolean
);

-- Applies staging.users to dw.dim_users as SCD Type 2 and returns (inserted, expired).
CREATE OR REPLACE FUNCTION dw.merge_dim_users(p_effective_at timestamptz DEFAULT now())
RETURNS TABLE (inserted_rows bigint, expired_rows bigint)
LANGUAGE plpgsql AS $$
DECLARE
    v_expired  bigint;
    v_inserted bigint;
BEGIN
    CREATE TEMP TABLE _incoming ON COMMIT DROP AS
    SELECT s.*,
           l.location_key,
           l.latitude  AS home_lat,
           l.longitude AS home_lon,
           -- Tracked (type-2) attributes only; account_open_date is immutable and kept from the first load.
           md5(concat_ws('|', s.card_id, s.home_city, s.home_country_code, s.card_network, s.card_tier,
                         s.segment, s.credit_limit_usd, s.has_chip_card)) AS row_hash
    FROM staging.users s
    JOIN dw.dim_location l ON l.city = s.home_city AND l.country_code = s.home_country_code;

    -- Close out current versions whose tracked attributes changed.
    UPDATE dw.dim_users d
       SET valid_to = p_effective_at, is_current = false
      FROM _incoming i
     WHERE d.user_id = i.user_id AND d.is_current AND d.row_hash <> i.row_hash;
    GET DIAGNOSTICS v_expired = ROW_COUNT;

    -- Insert brand-new users and new versions of changed users.
    INSERT INTO dw.dim_users (user_id, card_id, home_location_key, home_city, home_country_code, home_lat,
                              home_lon, card_network, card_tier, segment, account_open_date, credit_limit_usd,
                              has_chip_card, row_hash, valid_from)
    SELECT i.user_id, i.card_id, i.location_key, i.home_city, i.home_country_code, i.home_lat, i.home_lon,
           i.card_network, i.card_tier, i.segment, i.account_open_date, i.credit_limit_usd, i.has_chip_card,
           i.row_hash, p_effective_at
      FROM _incoming i
     WHERE NOT EXISTS (SELECT 1 FROM dw.dim_users d WHERE d.user_id = i.user_id AND d.is_current);
    GET DIAGNOSTICS v_inserted = ROW_COUNT;

    RETURN QUERY SELECT v_inserted, v_expired;
END $$;

-- -----------------------------------------------------------------------------
-- Facts
-- -----------------------------------------------------------------------------

-- Grain: one row per authorised card transaction. Range-partitioned by day so
-- retention is a cheap DROP/DETACH PARTITION and time-bounded scans prune.
CREATE TABLE IF NOT EXISTS dw.fact_transactions (
    transaction_id          uuid           NOT NULL,          -- degenerate dimension
    event_ts                timestamptz    NOT NULL,
    date_key                integer        NOT NULL,
    user_key                bigint         NOT NULL,
    merchant_key            bigint         NOT NULL,
    location_key            integer        NOT NULL,
    amount                  numeric(14, 2) NOT NULL,
    currency_code           char(3)        NOT NULL,
    amount_usd              numeric(14, 2) NOT NULL,
    channel                 text           NOT NULL,
    entry_mode              text           NOT NULL,
    txn_lat                 double precision,
    txn_lon                 double precision,
    -- real-time features computed by the stateful streaming operator
    distance_from_home_km   real,
    km_from_prev            real,
    seconds_since_prev      real,
    implied_speed_kmh       real,
    txn_count_1m            smallint,
    txn_count_5m            smallint,
    amount_usd_5m           numeric(14, 2),
    distinct_merchants_5m   smallint,
    small_txn_count_5m      smallint,
    amount_zscore           real,
    -- rule-engine output
    fraud_score             numeric(5, 4)  NOT NULL,
    risk_level              text           NOT NULL,
    is_flagged              boolean        NOT NULL,
    reason_codes            text[]         NOT NULL DEFAULT '{}',
    -- lineage
    kafka_partition         integer,
    kafka_offset            bigint,
    kafka_ts                timestamptz,
    processed_at            timestamptz,
    loaded_at               timestamptz    NOT NULL DEFAULT now(),
    PRIMARY KEY (transaction_id, event_ts)
) PARTITION BY RANGE (event_ts);

CREATE TABLE IF NOT EXISTS dw.fact_transactions_default PARTITION OF dw.fact_transactions DEFAULT;

-- BRIN: tiny, ideal for append-mostly time-ordered data.
CREATE INDEX IF NOT EXISTS ix_fact_txn_event_ts_brin ON dw.fact_transactions USING brin (event_ts) WITH (pages_per_range = 32);
CREATE INDEX IF NOT EXISTS ix_fact_txn_loaded_at_brin ON dw.fact_transactions USING brin (loaded_at) WITH (pages_per_range = 32);
-- B-tree: point/range lookups by entity.
CREATE INDEX IF NOT EXISTS ix_fact_txn_user_ts ON dw.fact_transactions (user_key, event_ts DESC);
CREATE INDEX IF NOT EXISTS ix_fact_txn_merchant_ts ON dw.fact_transactions (merchant_key, event_ts DESC);
CREATE INDEX IF NOT EXISTS ix_fact_txn_flagged ON dw.fact_transactions (event_ts DESC) WHERE is_flagged;

-- Creates missing daily partitions for [p_start, p_start + p_days). Rows that already
-- landed in the DEFAULT partition for that range are moved into the new partition.
CREATE OR REPLACE FUNCTION dw.ensure_daily_partitions(p_start date, p_days integer)
RETURNS integer LANGUAGE plpgsql AS $$
DECLARE
    v_day      date;
    v_lo       timestamptz;
    v_hi       timestamptz;
    v_name     text;
    v_created  integer := 0;
BEGIN
    FOR i IN 0 .. p_days - 1 LOOP
        v_day  := p_start + i;
        v_name := 'fact_transactions_' || to_char(v_day, 'YYYYMMDD');
        CONTINUE WHEN to_regclass('dw.' || v_name) IS NOT NULL;

        v_lo := v_day::timestamp AT TIME ZONE 'UTC';
        v_hi := (v_day + 1)::timestamp AT TIME ZONE 'UTC';

        IF EXISTS (SELECT 1 FROM dw.fact_transactions_default WHERE event_ts >= v_lo AND event_ts < v_hi) THEN
            -- Postgres refuses to attach a range the DEFAULT partition already holds rows for,
            -- so park those rows, create the partition, then re-insert (routes to the new one).
            CREATE TEMP TABLE IF NOT EXISTS _default_rows (LIKE dw.fact_transactions) ON COMMIT DROP;
            TRUNCATE _default_rows;
            INSERT INTO _default_rows
                SELECT * FROM dw.fact_transactions_default WHERE event_ts >= v_lo AND event_ts < v_hi;
            DELETE FROM dw.fact_transactions_default WHERE event_ts >= v_lo AND event_ts < v_hi;
            EXECUTE format('CREATE TABLE dw.%I PARTITION OF dw.fact_transactions FOR VALUES FROM (%L) TO (%L)',
                           v_name, v_lo, v_hi);
            INSERT INTO dw.fact_transactions SELECT * FROM _default_rows;
        ELSE
            EXECUTE format('CREATE TABLE dw.%I PARTITION OF dw.fact_transactions FOR VALUES FROM (%L) TO (%L)',
                           v_name, v_lo, v_hi);
        END IF;
        v_created := v_created + 1;
    END LOOP;
    RETURN v_created;
END $$;

SELECT dw.ensure_daily_partitions(current_date - 7, 45);

-- Grain: one row per transaction the rule engine flagged. Carries case status,
-- which is resolved by chargebacks (confirmed) or label maturity (false positive).
CREATE TABLE IF NOT EXISTS dw.fact_fraud_alerts (
    alert_id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    transaction_id      uuid           NOT NULL UNIQUE,
    event_ts            timestamptz    NOT NULL,
    date_key            integer        NOT NULL,
    user_key            bigint         NOT NULL,
    merchant_key        bigint         NOT NULL,
    amount_usd          numeric(14, 2) NOT NULL,
    fraud_score         numeric(5, 4)  NOT NULL,
    risk_level          text           NOT NULL,
    reason_codes        text[]         NOT NULL,
    status              text           NOT NULL DEFAULT 'OPEN'
                        CHECK (status IN ('OPEN', 'CONFIRMED_FRAUD', 'FALSE_POSITIVE')),
    status_updated_at   timestamptz,
    created_at          timestamptz    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_alerts_created_at ON dw.fact_fraud_alerts (created_at DESC);
CREATE INDEX IF NOT EXISTS ix_alerts_event_ts ON dw.fact_fraud_alerts (event_ts DESC);
CREATE INDEX IF NOT EXISTS ix_alerts_status ON dw.fact_fraud_alerts (status) WHERE status = 'OPEN';

-- Grain: one row per dispute raised by a cardholder (delayed ground-truth label).
CREATE TABLE IF NOT EXISTS dw.fact_chargebacks (
    chargeback_id   uuid           PRIMARY KEY,
    transaction_id  uuid           NOT NULL,
    user_key        bigint         NOT NULL,
    reason_code     text           NOT NULL,
    amount          numeric(14, 2) NOT NULL,
    currency_code   char(3)        NOT NULL,
    amount_usd      numeric(14, 2) NOT NULL,
    reported_ts     timestamptz    NOT NULL,
    loaded_at       timestamptz    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_chargebacks_txn ON dw.fact_chargebacks (transaction_id);
CREATE INDEX IF NOT EXISTS ix_chargebacks_reported ON dw.fact_chargebacks (reported_ts DESC);

-- -----------------------------------------------------------------------------
-- Aggregates
-- -----------------------------------------------------------------------------

-- Written by the streaming job: 5-minute windows sliding every minute, emitted in
-- UPDATE mode and upserted, so rows converge to their final value as late data lands.
CREATE TABLE IF NOT EXISTS dw.agg_merchant_window_risk (
    merchant_key          bigint         NOT NULL,
    window_start          timestamptz    NOT NULL,
    window_end            timestamptz    NOT NULL,
    txn_count             integer        NOT NULL,
    total_amount_usd      numeric(16, 2) NOT NULL,
    max_amount_usd        numeric(14, 2) NOT NULL,
    approx_distinct_users integer        NOT NULL,
    flagged_count         integer        NOT NULL,
    avg_fraud_score       numeric(6, 4)  NOT NULL,
    updated_at            timestamptz    NOT NULL DEFAULT now(),
    PRIMARY KEY (merchant_key, window_start)
);
CREATE INDEX IF NOT EXISTS ix_merchant_window_start ON dw.agg_merchant_window_risk (window_start DESC);

-- Written by the nightly reconciliation job from the lakehouse (source of truth).
CREATE TABLE IF NOT EXISTS dw.agg_hourly_merchant_risk (
    hour_ts                 timestamptz    NOT NULL,
    date_key                integer        NOT NULL,
    merchant_key            bigint         NOT NULL,
    mcc                     char(4)        NOT NULL,
    txn_count               integer        NOT NULL,
    total_amount_usd        numeric(16, 2) NOT NULL,
    flagged_count           integer        NOT NULL,
    avg_fraud_score         numeric(6, 4)  NOT NULL,
    chargeback_count        integer        NOT NULL,
    fraud_chargeback_count  integer        NOT NULL,
    chargeback_amount_usd   numeric(16, 2) NOT NULL,
    computed_at             timestamptz    NOT NULL DEFAULT now(),
    PRIMARY KEY (hour_ts, merchant_key)
);
CREATE INDEX IF NOT EXISTS ix_hourly_merchant_date ON dw.agg_hourly_merchant_risk (date_key);

-- -----------------------------------------------------------------------------
-- Analyst-facing view
-- -----------------------------------------------------------------------------

CREATE OR REPLACE VIEW dw.v_transactions_enriched AS
SELECT f.transaction_id,
       f.event_ts,
       d.full_date,
       d.is_weekend,
       u.user_id,
       u.segment,
       u.card_tier,
       u.card_network,
       u.home_city,
       m.merchant_id,
       m.merchant_name,
       m.is_online,
       c.mcc,
       c.category_name,
       c.risk_tier AS category_risk_tier,
       l.city      AS txn_city,
       l.country_code AS txn_country,
       f.amount,
       f.currency_code,
       f.amount_usd,
       f.channel,
       f.entry_mode,
       f.distance_from_home_km,
       f.implied_speed_kmh,
       f.txn_count_5m,
       f.amount_zscore,
       f.fraud_score,
       f.risk_level,
       f.is_flagged,
       f.reason_codes,
       f.loaded_at
FROM dw.fact_transactions f
JOIN dw.dim_date d              ON d.date_key = f.date_key
JOIN dw.dim_users u             ON u.user_key = f.user_key
JOIN dw.dim_merchants m         ON m.merchant_key = f.merchant_key
JOIN dw.dim_merchant_category c ON c.mcc = m.mcc
JOIN dw.dim_location l          ON l.location_key = f.location_key;

-- -----------------------------------------------------------------------------
-- Pipeline observability
-- -----------------------------------------------------------------------------

-- One row per micro-batch per streaming query (written by a StreamingQueryListener).
CREATE TABLE IF NOT EXISTS ops.streaming_query_progress (
    run_id                     uuid        NOT NULL,
    batch_id                   bigint      NOT NULL,
    query_id                   uuid        NOT NULL,
    query_name                 text        NOT NULL,
    progress_ts                timestamptz NOT NULL,
    num_input_rows             bigint      NOT NULL,
    input_rows_per_second      double precision,
    processed_rows_per_second  double precision,
    batch_duration_ms          bigint,
    trigger_execution_ms       bigint,
    add_batch_ms               bigint,
    get_batch_ms               bigint,
    query_planning_ms          bigint,
    wal_commit_ms              bigint,
    watermark                  timestamptz,
    state_rows_total           bigint,
    state_memory_bytes         bigint,
    rows_dropped_by_watermark  bigint,
    max_offsets_behind_latest  bigint,
    progress_json              jsonb,
    PRIMARY KEY (run_id, batch_id)
);
CREATE INDEX IF NOT EXISTS ix_progress_query_ts ON ops.streaming_query_progress (query_name, progress_ts DESC);
CREATE INDEX IF NOT EXISTS ix_progress_ts ON ops.streaming_query_progress (progress_ts DESC);

CREATE TABLE IF NOT EXISTS ops.reconciliation_runs (
    run_id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    business_date       date        NOT NULL,
    started_at          timestamptz NOT NULL,
    finished_at         timestamptz,
    status              text        NOT NULL CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED')),
    lakehouse_rows      bigint,
    warehouse_rows      bigint,
    backfilled_rows     bigint,
    orphan_rows         bigint,
    alerts_confirmed    bigint,
    alerts_cleared      bigint,
    quarantined_rows    bigint,
    details             jsonb
);
CREATE INDEX IF NOT EXISTS ix_recon_date ON ops.reconciliation_runs (business_date DESC);

-- Read-only role for BI tools / the dashboard.
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'analytics_reader') THEN
        CREATE ROLE analytics_reader NOLOGIN;
    END IF;
END $$;
GRANT USAGE ON SCHEMA dw, ops TO analytics_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA dw, ops TO analytics_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA dw GRANT SELECT ON TABLES TO analytics_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA ops GRANT SELECT ON TABLES TO analytics_reader;
